server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: cards-app
          uri: http://localhost:8080
          predicates:
            - Path=/cards/**
          filters:
            - TokenValidationFilter

