server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: cards-app
          uri: http://localhost:8081
          predicates:
            - Path=/cards/**
        - id: user-app
          uri:  http://localhost:8080
          predicates:
            - Path=/api/v1/**

