spring:
  application:
    name: UserService
    DEBUG: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:
    access: ${ACCESS_SECRET}
    refresh: ${REFRESH_SECRET}
springdoc:
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
